version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - '5483:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: artimarkdb
    # volumes:
      # - ./postgres:/var/lib/postgresql/data
      # - ./postgresql.conf:/etc/postgresql.conf
      # - ./pg-data:/var/lib/postgresql/data